### ISSUE TITLE
Fragment com.ihsanbal.introview.FragmentPage must be a public static class to be  properly recreated from instance state.

### ISSUE THREAD

**Issue by landsnail** [ihsanbal/SlidingIntoView#2]
there throw an exception which named : IllegalStateException
the error message：

java.lang.IllegalStateException: Fragment com.ihsanbal.introview.FragmentPage must be a public static class to be  properly recreated from instance state.
                                                               at android.support.v4.app.BackStackRecord.doAddOp(BackStackRecord.java:384)
                                                               at android.support.v4.app.BackStackRecord.add(BackStackRecord.java:375)
                                                               at android.support.v4.app.FragmentPagerAdapter.instantiateItem(FragmentPagerAdapter.java:103)
                                                               at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1034)
                                                               at android.support.v4.view.ViewPager.populate(ViewPager.java:1182)
                                                               at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                               at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                               at android.view.View.measure(View.java:18811)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                               at android.view.View.measure(View.java:18811)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                               at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                               at android.view.View.measure(View.java:18811)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                               at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:393)
                                                               at android.view.View.measure(View.java:18811)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                               at android.view.View.measure(View.java:18811)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                               at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                               at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                               at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                               at android.view.View.measure(View.java:18811)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                               at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                               at android.view.View.measure(View.java:18811)
                                                               at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2127)
                                                               at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1243)
                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1479)
                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                               at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:148)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by landsnail** [comment]
move all class of this library and  remove an annotation which named "@SuppressLint("ValidFragment")" that decorate the FragmentPage class  will work , i have done and it work well.

**Comment by preethamsridhar** [comment]
Move all class of this library to where?
